### ISSUE TITLE
Fatal Python error: _PyInterpreterState_Get(): no current thread state

### ISSUE THREAD

**Issue by ongbe** [zhujiang73/pytorch_mingw#1]
多个python版本
echo %PATH%
D:\develop\cmder\bin;D:\develop\cmder\vendor\bin;D:\develop\msys64\home\123456\.pyenv\versions\mingw64\bin;D:\develop\msys64\home\123456\.pyenv\bin;D:\develop\msys64\home\123456\.pyenv\bin;D:\develop\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\develop\cmder\vendor\conemu-maximus5;D:\develop\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\123456\AppData\Local\Microsoft\WindowsApps;D:\develop\cmder ;D:\develop\msys64\home\123456\.pyenv\Q-new-py36.env\Scripts;D:\develop\vim;D:\develop\node;D:\develop\msys64\mingw64\bin;D:\develop\msys64\usr\bin;D:\develop\msys64\usr\bin\usr\bin;D:\develop\cmder;D:\develop\msys64\home\123456\.pyenv\versions\mingw64\lib\python3.7\site-packages\torch\lib;D:\develop\msys64\home\123456\.pyenv\versions\mingw64\lib

python var_back.py
Fatal Python error: _PyInterpreterState_Get(): no current thread state
Python runtime state: unknown

**Comment by zhujiang73** [comment]
中文，那好办了，我英语确实不行。:-)

这个 pytorch_mingw 应该只适用于 msys2/mingw64  python 3.8 环境，如果系统启动了其它版本的 python 可能会出错。
